'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TambahRekamMedis

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tbx_idrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_idrm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_cek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cek As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbx_idpasien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_idpasien As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_idreg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_idreg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_kondisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_kondisi As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbx_stole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_stole As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_respirate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_respirate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_suhu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_suhu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_nadi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_nadi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_berat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_berat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_tinggi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_tinggi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_anamnesia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_anamnesia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bul_obat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bul_obat As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''bul_terapi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bul_terapi As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''btn_selesai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_selesai As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''div_obat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_obat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbx_obat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_obat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_obat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_obat As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gdv_obat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_obat As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''div_terapi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_terapi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbx_terapi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_terapi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_terapi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_terapi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gdv_terapi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_terapi As Global.System.Web.UI.WebControls.GridView
End Class
